"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Download, Loader2, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useFileTransferSession } from "../hooks/useFileTransferSession";

const formatBytes = (bytes: number) => {
  if (!Number.isFinite(bytes)) return "0 B";
  const units = ["B", "KB", "MB", "GB", "TB"];
  let value = bytes;
  let unitIndex = 0;
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex++;
  }
  return `${value.toFixed(value >= 10 || unitIndex === 0 ? 1 : 2)} ${units[unitIndex]}`;
};

export default function JoinRoomPage() {
  const { status, progress, error, receivedFile, connectToRoom, resetReceivedFile } = useFileTransferSession({
    role: "receiver",
  });
  const [roomInput, setRoomInput] = useState("");
  const [isJoining, setIsJoining] = useState(false);
  const [localError, setLocalError] = useState<string | null>(null);

  const handleJoin = async () => {
    const trimmed = roomInput.trim();
    if (!trimmed) {
      setLocalError("Room ID is required");
      return;
    }

    try {
      setLocalError(null);
      setIsJoining(true);
      await connectToRoom(trimmed);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to join the room";
      setLocalError(message);
    } finally {
      setIsJoining(false);
    }
  };

  const feedback = localError ?? error;

  return (
    <div className="mx-auto flex max-w-4xl flex-col gap-8 px-4 py-12">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <Button asChild variant="outline" className="gap-2">
          <Link href="/products/EncryptFileShare">
            <ArrowLeft className="size-4" />
            Back to actions
          </Link>
        </Button>
        <div className="text-right">
          <p className="text-sm uppercase tracking-wide text-muted-foreground">Step 2</p>
          <h1 className="text-2xl font-semibold">Join a room & receive the file</h1>
        </div>
      </div>

      <Card className="border-border/80">
        <CardHeader>
          <CardTitle>Join by room ID</CardTitle>
          <CardDescription>Paste the room ID shared by the sender. Once both peers are connected, the encrypted transfer begins automatically.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <label className="text-sm font-medium text-foreground" htmlFor="room-id-input">
              Room ID
            </label>
            <input
              id="room-id-input"
              value={roomInput}
              onChange={(event) => setRoomInput(event.target.value)}
              placeholder="Enter the 8-character room ID"
              className="w-full rounded-lg border border-border/80 bg-background px-3 py-3 text-base tracking-[0.3em] focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"
            />
            <p className="text-xs text-muted-foreground">The room ID is generated by the sender and expires when either peer disconnects.</p>
          </div>

          <Button className="h-12 w-full text-base font-semibold" onClick={handleJoin} disabled={isJoining}>
            {isJoining ? (
              <>
                <Loader2 className="mr-2 size-5 animate-spin" />
                Joining room...
              </>
            ) : (
              "Join room"
            )}
          </Button>

          <div className="rounded-xl border border-border/70 bg-muted/20 p-4">
            <p className="text-sm font-medium text-foreground">Status</p>
            <p className="text-sm text-muted-foreground">{status}</p>
            {(progress ?? 0) > 0 && (
              <div className="mt-3">
                <div className="flex items-center justify-between text-xs text-muted-foreground">
                  <span>Download progress</span>
                  <span>{progress.toFixed(1)}%</span>
                </div>
                <div className="mt-1 h-2 w-full overflow-hidden rounded-full bg-muted">
                  <div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.min(progress, 100)}%` }} />
                </div>
              </div>
            )}
            {feedback && <p className="mt-3 text-sm text-destructive">{feedback}</p>}
          </div>
        </CardContent>
      </Card>

      <Card className="border-border/80">
        <CardHeader>
          <CardTitle>Transfer result</CardTitle>
          <CardDescription>When the sender finishes streaming the file, it will appear below. Downloads stay in your browser and are not stored on the server.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {receivedFile ? (
            <>
              <div className="rounded-xl border border-border/60 bg-background px-4 py-3">
                <p className="text-base font-semibold text-foreground">{receivedFile.name}</p>
                <p className="text-sm text-muted-foreground">
                  {formatBytes(receivedFile.size)} • {receivedFile.mimeType}
                </p>
              </div>
              <div className="flex flex-wrap gap-3">
                <Button asChild className="gap-2">
                  <a href={receivedFile.downloadUrl} download={receivedFile.name}>
                    <Download className="size-4" />
                    Download file
                  </a>
                </Button>
                <Button variant="ghost" className="gap-2" onClick={resetReceivedFile}>
                  <RefreshCw className="size-4" />
                  Clear file
                </Button>
              </div>
            </>
          ) : (
            <div className="rounded-xl border border-dashed border-border/70 bg-muted/30 px-4 py-6 text-center text-sm text-muted-foreground">Waiting for the sender to start streaming the file...</div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
