// "use client";

// import { useState } from "react";
// import Link from "next/link";
// import { ArrowLeft, Download, Loader2, RefreshCw } from "lucide-react";
// import { Button } from "@/components/ui/button";
// import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
// import { useFileTransferSession } from "../hooks/useFileTransferSession";

// const formatBytes = (bytes: number) => {
//   if (!Number.isFinite(bytes)) return "0 B";
//   const units = ["B", "KB", "MB", "GB", "TB"];
//   let value = bytes;
//   let unitIndex = 0;
//   while (value >= 1024 && unitIndex < units.length - 1) {
//     value /= 1024;
//     unitIndex++;
//   }
//   return `${value.toFixed(value >= 10 || unitIndex === 0 ? 1 : 2)} ${units[unitIndex]}`;
// };

// export default function JoinRoomPage() {
//   const { status, progress, error, receivedFile, connectToRoom, resetReceivedFile } = useFileTransferSession({
//     role: "receiver",
//   });
//   const [roomInput, setRoomInput] = useState("");
//   const [isJoining, setIsJoining] = useState(false);
//   const [localError, setLocalError] = useState<string | null>(null);

//   const handleJoin = async () => {
//     const trimmed = roomInput.trim();
//     if (!trimmed) {
//       setLocalError("Room ID is required");
//       return;
//     }

//     try {
//       setLocalError(null);
//       setIsJoining(true);
//       await connectToRoom(trimmed);
//     } catch (err) {
//       const message = err instanceof Error ? err.message : "Failed to join the room";
//       setLocalError(message);
//     } finally {
//       setIsJoining(false);
//     }
//   };

//   const feedback = localError ?? error;

//   return (
//     <div className="mx-auto flex max-w-4xl flex-col gap-8 px-4 py-12">
//       <div className="flex flex-wrap items-center justify-between gap-4">
//         <Button asChild variant="outline" className="gap-2">
//           <Link href="/products/EncryptFileShare">
//             <ArrowLeft className="size-4" />
//             Back to actions
//           </Link>
//         </Button>
//         <div className="text-right">
//           <p className="text-sm uppercase tracking-wide text-muted-foreground">Step 2</p>
//           <h1 className="text-2xl font-semibold">Join a room & receive the file</h1>
//         </div>
//       </div>

//       <Card className="border-border/80">
//         <CardHeader>
//           <CardTitle>Join by room ID</CardTitle>
//           <CardDescription>Paste the room ID shared by the sender. Once both peers are connected, the encrypted transfer begins automatically.</CardDescription>
//         </CardHeader>
//         <CardContent className="space-y-6">
//           <div className="space-y-2">
//             <label className="text-sm font-medium text-foreground" htmlFor="room-id-input">
//               Room ID
//             </label>
//             <input
//               id="room-id-input"
//               value={roomInput}
//               onChange={(event) => setRoomInput(event.target.value)}
//               placeholder="Enter the 8-character room ID"
//               className="w-full rounded-lg border border-border/80 bg-background px-3 py-3 text-base tracking-[0.3em] focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"
//             />
//             <p className="text-xs text-muted-foreground">The room ID is generated by the sender and expires when either peer disconnects.</p>
//           </div>

//           <Button className="h-12 w-full text-base font-semibold" onClick={handleJoin} disabled={isJoining}>
//             {isJoining ? (
//               <>
//                 <Loader2 className="mr-2 size-5 animate-spin" />
//                 Joining room...
//               </>
//             ) : (
//               "Join room"
//             )}
//           </Button>

//           <div className="rounded-xl border border-border/70 bg-muted/20 p-4">
//             <p className="text-sm font-medium text-foreground">Status</p>
//             <p className="text-sm text-muted-foreground">{status}</p>
//             {(progress ?? 0) > 0 && (
//               <div className="mt-3">
//                 <div className="flex items-center justify-between text-xs text-muted-foreground">
//                   <span>Download progress</span>
//                   <span>{progress.toFixed(1)}%</span>
//                 </div>
//                 <div className="mt-1 h-2 w-full overflow-hidden rounded-full bg-muted">
//                   <div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.min(progress, 100)}%` }} />
//                 </div>
//               </div>
//             )}
//             {feedback && <p className="mt-3 text-sm text-destructive">{feedback}</p>}
//           </div>
//         </CardContent>
//       </Card>

//       <Card className="border-border/80">
//         <CardHeader>
//           <CardTitle>Transfer result</CardTitle>
//           <CardDescription>When the sender finishes streaming the file, it will appear below. Downloads stay in your browser and are not stored on the server.</CardDescription>
//         </CardHeader>
//         <CardContent className="space-y-4">
//           {receivedFile ? (
//             <>
//               <div className="rounded-xl border border-border/60 bg-background px-4 py-3">
//                 <p className="text-base font-semibold text-foreground">{receivedFile.name}</p>
//                 <p className="text-sm text-muted-foreground">
//                   {formatBytes(receivedFile.size)} • {receivedFile.mimeType}
//                 </p>
//               </div>
//               <div className="flex flex-wrap gap-3">
//                 <Button asChild className="gap-2">
//                   <a href={receivedFile.downloadUrl} download={receivedFile.name}>
//                     <Download className="size-4" />
//                     Download file
//                   </a>
//                 </Button>
//                 <Button variant="ghost" className="gap-2" onClick={resetReceivedFile}>
//                   <RefreshCw className="size-4" />
//                   Clear file
//                 </Button>
//               </div>
//             </>
//           ) : (
//             <div className="rounded-xl border border-dashed border-border/70 bg-muted/30 px-4 py-6 text-center text-sm text-muted-foreground">Waiting for the sender to start streaming the file...</div>
//           )}
//         </CardContent>
//       </Card>
//     </div>
//   );
// }


"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Download, Loader2, RefreshCw, Radio, HardDriveDownload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useFileTransferSession } from "../hooks/useFileTransferSession";

// Helper for formatting file size
const formatBytes = (bytes: number) => {
  if (!Number.isFinite(bytes)) return "0 B";
  const units = ["B", "KB", "MB", "GB", "TB"];
  let value = bytes;
  let unitIndex = 0;
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex++;
  }
  return `${value.toFixed(value >= 10 || unitIndex === 0 ? 1 : 2)} ${units[unitIndex]}`;
};

export default function JoinRoomPage() {
  const { status, progress, error, receivedFile, connectToRoom, resetReceivedFile } = useFileTransferSession({
    role: "receiver",
  });
  const [roomInput, setRoomInput] = useState("");
  const [isJoining, setIsJoining] = useState(false);
  const [localError, setLocalError] = useState<string | null>(null);

  const handleJoin = async () => {
    const trimmed = roomInput.trim();
    if (!trimmed) {
      setLocalError("Room ID is required");
      return;
    }

    try {
      setLocalError(null);
      setIsJoining(true);
      await connectToRoom(trimmed);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to join the room";
      setLocalError(message);
    } finally {
      setIsJoining(false);
    }
  };

  const feedback = localError ?? error;

  return (
    <div className="min-h-screen w-full bg-[#050505] text-white selection:bg-[#eac2ff] selection:text-[#050505] relative overflow-hidden">
      
      {/* Ambient Background Glows */}
      <div className="absolute top-[-10%] left-[-10%] w-[500px] h-[500px] bg-[#eac2ff]/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[500px] h-[500px] bg-blue-500/10 rounded-full blur-[120px] pointer-events-none" />

      <div className="mx-auto flex max-w-3xl flex-col gap-8 px-6 py-20 relative z-10">
        
        {/* Header Navigation */}
        <div className="flex flex-wrap items-center justify-between gap-4">
          <Button 
            asChild 
            variant="ghost" 
            className="group gap-2 text-zinc-400 hover:text-[#eac2ff] hover:bg-[#eac2ff]/5 transition-colors pl-0"
          >
            <Link href="/products/EncryptFileShare">
              <div className="p-1 rounded-full border border-zinc-800 bg-zinc-900 group-hover:border-[#eac2ff]/30 transition-colors">
                 <ArrowLeft className="size-4" />
              </div>
              <span className="font-light">Back to actions</span>
            </Link>
          </Button>
          
          <div className="text-right">
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#eac2ff] mb-1">
              Receiver Mode
            </p>
            <h1 className="text-xl font-medium tracking-tight text-white/90">
              Join & Receive
            </h1>
          </div>
        </div>

        {/* Main Connection Card */}
        <Card className="border-white/10 bg-zinc-900/40 backdrop-blur-xl shadow-2xl shadow-black/50 overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-1 bg-linear-to-r from-transparent via-[#eac2ff]/50 to-transparent opacity-50" />
          
          <CardHeader className="pb-2">
            <div className="flex items-center gap-3 mb-2">
              <div className="p-2.5 rounded-lg bg-[#eac2ff]/10 border border-[#eac2ff]/20">
                <Radio className="size-5 text-[#eac2ff]" />
              </div>
              <CardTitle className="text-lg font-medium text-white">Connection Setup</CardTitle>
            </div>
            <CardDescription className="text-zinc-400">
              Enter the unique 8-character ID provided by the sender.
            </CardDescription>
          </CardHeader>
          
          <CardContent className="space-y-8 pt-6">
            <div className="space-y-3">
              <label className="text-xs font-medium text-zinc-500 uppercase tracking-wider ml-1" htmlFor="room-id-input">
                Room Identifier
              </label>
              <div className="relative group">
                <input
                  id="room-id-input"
                  value={roomInput}
                  onChange={(event) => setRoomInput(event.target.value)}
                  placeholder="X Y Z 1 2 3"
                  className="w-full rounded-xl border border-white/10 bg-black/40 px-4 py-4 text-center text-2xl font-mono tracking-[0.5em] text-[#eac2ff] placeholder:text-zinc-700 focus:border-[#eac2ff]/50 focus:outline-none focus:ring-4 focus:ring-[#eac2ff]/10 transition-all uppercase shadow-inner"
                  maxLength={8}
                />
                {/* Subtle shine effect on input border */}
                <div className="absolute inset-0 rounded-xl ring-1 ring-inset ring-white/5 pointer-events-none group-hover:ring-white/10 transition-all" />
              </div>
            </div>

            <Button 
              className="h-14 w-full text-base font-medium bg-[#eac2ff] text-black hover:bg-[#d8a8ff] hover:shadow-[0_0_20px_-5px_rgba(234,194,255,0.4)] transition-all duration-300 rounded-xl" 
              onClick={handleJoin} 
              disabled={isJoining}
            >
              {isJoining ? (
                <>
                  <Loader2 className="mr-2 size-5 animate-spin opacity-70" />
                  Establishing Secure Link...
                </>
              ) : (
                "Join Room"
              )}
            </Button>

            {/* Status Indicator */}
            <div className="rounded-xl border border-white/5 bg-white/5 p-5 backdrop-blur-sm">
              <div className="flex items-center justify-between mb-2">
                 <p className="text-xs font-medium text-zinc-400 uppercase tracking-wide">Signal Status</p>
                 <div className={`h-2 w-2 rounded-full ${status === 'connected' ? 'bg-green-500 shadow-[0_0_8px_rgba(34,197,94,0.6)]' : 'bg-zinc-700'}`} />
              </div>
              
              <p className={`text-sm font-mono ${status === 'connected' ? 'text-green-400' : 'text-zinc-300'}`}>
                {status || "Ready to connect"}
              </p>
              
              {(progress ?? 0) > 0 && (
                <div className="mt-5 space-y-2">
                  <div className="flex items-center justify-between text-xs text-[#eac2ff]/80 font-mono">
                    <span>Decryption in progress...</span>
                    <span>{progress.toFixed(0)}%</span>
                  </div>
                  <div className="h-1.5 w-full overflow-hidden rounded-full bg-zinc-800">
                    <div 
                      className="h-full rounded-full bg-[#eac2ff] shadow-[0_0_10px_#eac2ff] transition-all duration-300 ease-out" 
                      style={{ width: `${Math.min(progress, 100)}%` }} 
                    />
                  </div>
                </div>
              )}
              
              {feedback && (
                <div className="mt-4 p-3 rounded-lg bg-red-500/10 border border-red-500/20 text-red-400 text-sm">
                  {feedback}
                </div>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Results Section */}
        <div className="space-y-4">
          <h2 className="text-sm font-medium text-zinc-500 uppercase tracking-widest pl-1">Received Assets</h2>
          
          <Card className={`border-white/10 bg-zinc-900/20 backdrop-blur-md transition-all duration-500 ${receivedFile ? 'opacity-100 translate-y-0' : 'opacity-80'}`}>
            <CardContent className="p-6">
              {receivedFile ? (
                <div className="flex flex-col gap-6">
                  <div className="flex items-start gap-4 p-4 rounded-xl border border-[#eac2ff]/20 bg-[#eac2ff]/5">
                    <div className="p-3 rounded-lg bg-[#eac2ff]/10 text-[#eac2ff]">
                      <HardDriveDownload className="size-6" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-lg font-medium text-white truncate">{receivedFile.name}</p>
                      <div className="flex items-center gap-2 mt-1 text-xs text-zinc-400 font-mono">
                         <span className="px-2 py-0.5 rounded bg-white/5 border border-white/5">
                           {formatBytes(receivedFile.size)}
                         </span>
                         <span>•</span>
                         <span className="truncate max-w-[150px]">{receivedFile.mimeType}</span>
                      </div>
                    </div>
                  </div>

                  <div className="flex flex-wrap gap-3">
                    <Button asChild className="flex-1 bg-white text-black hover:bg-zinc-200 h-11 font-medium rounded-lg">
                      <a href={receivedFile.downloadUrl} download={receivedFile.name}>
                        <Download className="mr-2 size-4" />
                        Save to Disk
                      </a>
                    </Button>
                    <Button 
                      variant="outline" 
                      className="flex-none border-white/10 hover:bg-white/5 hover:text-white h-11 rounded-lg text-zinc-400" 
                      onClick={resetReceivedFile}
                    >
                      <RefreshCw className="size-4" />
                    </Button>
                  </div>
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center py-8 text-center border-2 border-dashed border-white/5 rounded-xl bg-white/2">
                  <div className="size-12 rounded-full bg-zinc-800/50 flex items-center justify-center mb-3 text-zinc-600">
                    <Download className="size-5" />
                  </div>
                  <p className="text-sm text-zinc-500">Waiting for stream...</p>
                  <p className="text-xs text-zinc-700 mt-1">Files are decrypted locally in your browser</p>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
