import type { Metadata } from "next";
import "./globals.css";
import { AppProviders } from "@/components/providers/app-providers";
import CustomToast from "@/components/ui/CustomToast";

export const metadata: Metadata = {
  title: "SimplLx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className="min-h-screen bg-background antialiased">
        <AppProviders>
          {children}
          <CustomToast />
        </AppProviders>
      </body>
    </html>
  );
}
